### ISSUE TITLE
/editと/memorizeで画像の大きさが変わる

### ISSUE THREAD

**Issue by itt828** [hackathon-21-winter-18/frontend#38]
現状ピンは絶対座標を保存してるだけなので、画像の大きさがeditの時と異なると/memorizeで見たときにピンの位置がずれます
- ピンの座標を画像の左上からの比[0,1]×[0,1]とかで保存するとか?

**Comment by mehm8128** [comment]
画像の大きさ固定したから多分完
ピンのずれ直したら多分完全に直る
