### ISSUE TITLE
ログイン失敗時の文を変えた方がいい気がする。

### ISSUE THREAD

**Issue by kounosukexxx** [hackathon-21-winter-18/frontend#67]
今はユーザー名が違いますみたいな感じに書いてあって、そのユーザー名のユーザーが存在しないみたいになってる

**Comment by mehm8128** [comment]
これってどういうこと？
今は404が返ってきたときに「ユーザー名が間違っています」みたいに表示するようにしてるけど、ユーザー名間違ってる以外でも404になることがあるからみたいな？

**Comment by kounosukexxx** [comment]
あーーごめん。パスワード間違ってるときはちゃんとパスワードが違いますってでてるから大丈夫だ
