### ISSUE TITLE
notices機能の実装

### ISSUE THREAD

**Issue by kounosukexxx** [hackathon-21-winter-18/frontend#70]
- PUT api/palaces(templates)/share　でcreatedByもbodyに詰める。
- ユーザーアイコンのとなりとかにnoticesアイコンをつける。
- noticesアイコンを押したらGET api/notices を叩く&noticesの一覧をどこかに表示する。
- GET palaces/meを叩いた時unreadNoticesが返ってくるから、それをnoticesアイコンの右上とかに表示する。(lineの未読数みたいな感じで。)
- templateからpalaceを抽出して保存(POST api/templates/me)する時にもcreatedByをボディに詰める。(自分のIDじゃなくてpalaceのcreatedByをつめることに注意)
- 一応swaggerはswagger-1.2ブランチで更新するつもり
- このnoticesは忘却曲線のやつでも使うつもり

以上をお願いm(__)m

**Comment by kounosukexxx** [comment]
unreadNoticesは0の時は表示しなくていいと思う

**Comment by mehm8128** [comment]
・「GET palaces/meを叩いた時unreadNoticesが返ってくる」のところって、whoamI叩いたときに返すのじゃ駄目かな？
・「templateからpalaceを抽出して保存(POST api/templates/me)する時にもcreatedByをボディに詰める」がよく分からなかった。templateのピンに単語を入れてpalaceを作るときってこと？ならPOST api/palaces/meな気がした

**Comment by kounosukexxx** [comment]
通知に公開されたpalaces, templates先のurlをはるつもりだからそれに前作ったGET palaces/:palaceID と templates/:templateID　のurlを張ってもらう感じになると思う。markdown形式になるように返すとかそうじゃなくていいとかは考える必要がある。特にurlを張らないといけないからどうしたほうがいいのかわかりかねる。

**Comment by mehm8128** [comment]
URLというか、公開されたpalaceとかtemplateのIDを返してもらえば暗記画面とかにルーティングできるはず(それを使ってピンとかの情報をGETする)

**Comment by mehm8128** [comment]
多分完
怪しければ修正する
