### ISSUE TITLE
プライバシーポリシーのurlを登録ボタンのページに張っといた方がよさそう

### ISSUE THREAD

**Issue by kounosukexxx** [hackathon-21-winter-18/frontend#97]
あと好みの問題だけど、体験版へっていうよりログインせずに使用とか、とりあえず使ってみるとかの方がよくない？それかそもそもそのページをはさまず、exploreとかしか使えないページから始めるとか。最後のやつの場合はプライバシーポリシーを書く場所を見てもらえるよう置く場所考える必要あるけど

**Comment by mehm8128** [comment]
完
